# Generated by Django 2.0 on 2020-05-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200522_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
