# Generated by Django 2.0 on 2020-05-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200522_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
