# Generated by Django 2.2 on 2020-06-02 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20200527_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.DateField(auto_now_add=True)),
                ('type', models.CharField(max_length=300)),
                ('code', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('o', 'out of service'), ('s', 'in service'), ('r', 'ready to service'), ('b', 'standby')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='master',
            name='power',
            field=models.CharField(choices=[('3.3', 'voltage 3.3'), ('5', 'voltage 5'), ('12', 'voltage 12')], default='5', max_length=3),
        ),
        migrations.AlterField(
            model_name='master',
            name='type',
            field=models.CharField(choices=[('pi3', 'raspberry pi 3'), ('pi4', 'raspberry pi 4'), ('zerow', 'raspberry pi zer w')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='register.Master'),
        ),
    ]
