# Generated by Django 2.2 on 2020-06-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20200602_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='master',
        ),
        migrations.DeleteModel(
            name='Master',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
