# Generated by Django 2.0 on 2020-05-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200519_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='code',
            field=models.IntegerField(),
        ),
    ]
